import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Google_Sans, Google_Sans_Flex, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/Navbar";

const fallbackOne = Geist({
  variable : "--font-fallback-one",
  subsets: ["latin"],
});

const fallbackTwo = Geist_Mono({
  variable : "--font-fallback-two",
  subsets: ["latin"],
});



const geistSans = Google_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  fallback: ["Geist", "sans-serif"],
  adjustFontFallback: false,
});

const geistMono = Google_Sans_Flex({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  fallback: ["Geist Mono", "monospace"],
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} ${fallbackOne.variable} ${fallbackTwo.variable} min-h-full flex flex-col bg-black`} suppressHydrationWarning>
        {children}
      <Toaster/>
      </body>
    </html>
  );
}
